Default Native Interface Security - Latest WildFly Documentation
================================================================

[[default-native-interface-security]]
Default Native Interface Security
---------------------------------

The native interface shares the same security configuration as the http
interface, however we also support a local authentication mechanism
which means that the CLI can authenticate against the local WildFly
instance without prompting the user for a username and password.  This
mechanism only works if the user running the CLI has read access to the
standalone/tmp/auth folder or domain/tmp/auth folder under the
respective WildFly installation - if the local mechanism fails then the
CLI will fallback to prompting for a username and password for a user
configured as in 
https://docs.jboss.org/author/display/AS71/Default+HTTP+Interface+Security[Default
HTTP Interface Security].

Establishing a CLI connection to a remote server will require a username
and password by default.
