Remote JNDI Reference - Latest WildFly Documentation
====================================================

[[remote-jndi-reference]]
Remote JNDI Reference
---------------------

[[remote-jndi]]
Remote JNDI
~~~~~~~~~~~

WildFly supports two different types of remote JNDI. The old jnp based
JNDI implementation used in JBoss AS versions prior to 7.x is no longer
supported.

[[remote]]
remote:
^^^^^^^

The `remote:` protocol uses the WildFly remoting protocol to lookup
items from the servers local JNDI. To use it, you must have the
appropriate jars on the class path, if you are maven user can be done
simply by adding the following to your `pom.xml`:

[source,brush:,xml;,gutter:,false;]
----
<dependency>
  <groupId>org.wildfly</groupId>
  <artifactId>wildfly-ejb-client-bom</artifactId>
  <version>8.0.0.Final</version>
  <type>pom</type>
  <scope>compile</scope>
</dependency>
----

If you are not using maven a shaded jar that contains all required
classes +
can be found in the `bin/client` directory of WildFly's distribution.

[source,java]
----
final Properties env = new Properties();
env.put(Context.INITIAL_CONTEXT_FACTORY, org.jboss.naming.remote.client.InitialContextFactory.class.getName());
env.put(Context.PROVIDER_URL, "remote://localhost:4447");
remoteContext = new InitialContext(env);
----

[[ejb]]
ejb:
^^^^

The ejb: namespace is provided by the jboss-ejb-client library. This
protocol allows you to look up EJB's, using their application name,
module name, ejb name and interface type.

This is a client side JNDI implementation. Instead of looking up an EJB
on the server the lookup name contains enough information for the client
side library to generate a proxy with the EJB information. When you
invoke a method on this proxy it will use the current EJB client context
to perform the invocation. If the current context does not have a
connection to a server with the specified EJB deployed then an error
will occur. Using this protocol it is possible to look up EJB's that do
not actually exist, and no error will be thrown until the proxy is
actually used. The exception to this is stateful session beans, which
need to connect to a server when they are created in order to create the
session bean instance on the server.

Some examples are:

`ejb:myapp/myejbjar/MyEjbName!com.test.MyRemoteInterface` +
`ejb:myapp/myejbjar/MyStatefulName!comp.test.MyStatefulRemoteInterface?stateful`

The first example is a lookup of a singleton, stateless or EJB 2.x home
interface. This lookup will not hit the server, instead a proxy will be
generated for the remote interface specified in the name. The second
example is for a stateful session bean, in this case the JNDI lookup
will hit the server, in order to tell the server to create the SFSB
session.

For more details on how the server connections are configured, please
see link:EJB_invocations_from_a_remote_client_using_JNDI.html[EJB
invocations from a remote client using JNDI].
